services:
    docker-cli-frontend:
        container_name: docker-cli-frontend-container
        image: docker-cli-frontend:v1
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        env_file:
            - .env




